spring:
  application:
    name: dubbo-provider-demo
server:
  port: 9090
dubbo:
  scan:
    base-packages: team.wenwhite.springboot.dubbo
  application:
    id: dubbo-provider
    name: dubbo-provider
  protocol:
    id: dubbo
    name: dubbo
    port: 12345
    status: server
  registry:
    id: my-reg
    address: zookeeper://***.***.***.**:****
endpoints:
  dubbo:
    enabled: true
management:
  port: 9091
  health:
    dubbo:
      status:
        extras: load,threadpool
        default: memory
